/* „Stark mit Leo" (Mindset & Freundschaft) – MC-Pools und Mut-Sätze
   aus der Alt-App v1.86. Identifikationsfiguren (Ben/Mia/Tom) statt
   direkter Ansprache; jede Antwort hat einen bestärkenden Tipp. */
export const STARK_DATEN={
  easy:[
    {kontext:"Auf dem Schulhof spielen Kinder Fangen. Ben möchte mitmachen.",
     f:"Was klappt am besten?", r:"Freundlich fragen: „Darf ich mitspielen?“",
     x:["Einfach dazwischenrennen und alle erschrecken","Nichts sagen und traurig zugucken"],
     tipp:"Eine freundliche Frage wirkt fast immer – die meisten sagen Ja!"},
    {kontext:"Mia erzählt in der Gruppe von ihrem Wochenende. Du möchtest auch etwas erzählen.",
     f:"Was machst du?", r:"Mia ausreden lassen – und dann erzählen",
     x:["Lauter reden als Mia","Dazwischenrufen: „Ich war auch weg!“"],
     tipp:"Wer zuhört, bekommt auch Zuhörer. Dein Moment kommt gleich danach!"},
    {f:"Du möchtest, dass die anderen dich beachten. Was wirkt am besten?",
     r:"Etwas Nettes sagen oder jemandem helfen",
     x:["Laut Quatsch machen","Andere ärgern"],
     tipp:"Mit Quatsch bekommst du kurz Blicke – mit Freundlichkeit echte Freunde."},
    {kontext:"Tom hat ein tolles Tor geschossen.",
     f:"Was sagt ein guter Freund?", r:"„Stark! Super Tor!“",
     x:["„Das kann ich viel besser!“","Nichts – einfach wegschauen"],
     tipp:"Ein Kompliment kostet nichts – und macht euch beide froh."},
    {f:"Ein Kind aus deiner Klasse steht in der Pause ganz alleine. Was tust du?",
     r:"Hingehen und fragen: „Willst du mitmachen?“",
     x:["So tun, als wäre es nicht da","Warten, dass es von selbst kommt"],
     tipp:"Genau so beginnen Freundschaften: Einer traut sich und geht den ersten Schritt."},
    {kontext:"Beim Spielen läuft es nicht so, wie du willst. Du merkst, dass du wütend wirst.",
     f:"Was hilft dir jetzt?", r:"Tief atmen und sagen: „Ich brauche kurz eine Pause.“",
     x:["Das Spiel kaputt machen","Ganz laut schreien"],
     tipp:"Gefühle in Worten sagen – das verstehen alle. Und die Wut wird kleiner."},
    {f:"Was macht dich zu einem guten Freund?",
     r:"Zuhören, teilen und freundlich sein",
     x:["Immer der Beste sein","Die coolsten Sachen besitzen"],
     tipp:"Freunde suchen keinen Superhelden – sie suchen jemanden, der nett zu ihnen ist."},
    {kontext:"Lisa kichert, weil du im Diktat einen Fehler gemacht hast.",
     f:"Was denkst du am besten?", r:"„Fehler passieren – daraus lerne ich.“",
     x:["„Ich kann das eben nicht.“","„Ich mache nie wieder mit.“"],
     tipp:"Fehler sind Trainings-Schritte. Jeder macht sie – wirklich jeder, auch Erwachsene."},
    {f:"Du willst in der Klasse etwas sagen, bist aber aufgeregt. Was hilft?",
     r:"Einmal tief atmen und langsam sprechen",
     x:["Ganz schnell alles herausreden","Lieber gar nichts sagen"],
     tipp:"Langsam sprechen wirkt stark – und deine Gedanken bleiben sortiert."},
    {kontext:"Zwei Kinder streiten sich um den Ball.",
     f:"Was ist ein fairer Vorschlag?", r:"„Wir wechseln uns ab!“",
     x:["Den Ball einfach wegnehmen","Beim Streiten mitschreien"],
     tipp:"Wer faire Ideen hat, wird gern zum Spielen eingeladen."},
    {f:"Jemand sagt „Stopp!“ beim Toben. Was tust du?",
     r:"Sofort aufhören",
     x:["Weitermachen – war ja nur Spaß","Noch wilder toben"],
     tipp:"„Stopp“ gilt immer. Wer es respektiert, dem vertrauen die anderen."},
    {kontext:"Beim Pausenfußball kommt Ben kaum an den Ball.",
     f:"Was kann er sagen, um gut mitzumachen?", r:"„Ich gehe ins Tor!“ oder „Gib mir mal einen Pass!“",
     x:["Beleidigt vom Platz gehen","Heimlich den Ball nehmen und wegrennen"],
     tipp:"Ein Spiel hat viele Rollen – frag nach der, die dir liegt. Mitmachen zählt, nicht Tore."},
    {kontext:"Ben stöhnt: „Ich kann einfach kein Fußball!“",
     f:"Was stimmt wirklich?", r:"Er kann es NOCH nicht so gut – Üben verändert das",
     x:["Können ist angeboren – da kann man nichts machen","Dann soll er es eben lassen"],
     tipp:"Das Zauberwort heißt NOCH. Alles, was du kannst, konntest du mal nicht."},
    {kontext:"Ben hat aus Versehen Lukas' Bauklotz-Turm umgeworfen. Lukas ist richtig traurig.",
     f:"Wie macht Ben es wieder gut?", r:"Sich entschuldigen und anbieten, beim Neubauen zu helfen",
     x:["So tun, als wäre nichts gewesen","Sagen: „Ist doch nur ein Turm!“"],
     tipp:"Fehler passieren – Wiedergutmachen macht sie kleiner und dich größer."},
    {f:"Wie zeigst du jemandem, dass du wirklich zuhörst?",
     r:"Anschauen, nicken, nachfragen",
     x:["Nebenbei etwas anderes machen","Schnell vom eigenen Thema anfangen"],
     tipp:"Zuhören ist ein Geschenk – und kommt fast immer zu dir zurück."},
    {kontext:"Ein Kind stolpert im Flur, ein paar lachen los.",
     f:"Was machst du?", r:"Nicht mitlachen – hingehen und fragen: „Alles okay?“",
     x:["Mitlachen, damit du dazugehörst","Schnell weitergehen"],
     tipp:"Freundlich sein ist keine Schwäche – es ist deine Superkraft."},
    {kontext:"Du hast Tom versprochen, heute mit ihm zu spielen. Jetzt lädt dich ein anderes Kind zu etwas ein, das cooler klingt.",
     f:"Was macht ein guter Freund?", r:"Zu Tom stehen – ein Versprechen gilt",
     x:["Einfach nicht zu Tom gehen","Tom erzählen, du wärst krank"],
     tipp:"Wer sein Wort hält, dem vertrauen die anderen. Das ist mehr wert als jedes coole Angebot."}
  ],
  hard:[
    {kontext:"Ben spielt im Verein Fußball, weil fast alle aus seiner Klasse dort sind. Aber eigentlich mag er viel lieber Schach und Klettern.",
     f:"Was rätst du Ben?", r:"Mach das, was DIR Spaß macht – dort findest du Freunde, die wirklich zu dir passen",
     x:["Bleib beim Fußball, sonst gehörst du nicht dazu","Hör am besten mit allen Hobbys auf"],
     tipp:"Bei dem, was du liebst, bist du ganz du selbst – und genau so findet man die besten Freunde."},
    {kontext:"Die Gruppe lacht über einen Witz, der ein Kind traurig macht.",
     f:"Was ist mutig?", r:"Nicht mitlachen – und dem Kind beistehen",
     x:["Mitlachen, um dazuzugehören","So tun, als hättest du nichts gehört"],
     tipp:"Mut heißt manchmal: anders sein als die Gruppe. Genau das macht dich stark."},
    {f:"Du darfst bei einem Spiel gerade nicht mitmachen. Was ist die stärkste Reaktion?",
     r:"„Okay – ich frage später nochmal oder spiele solange etwas anderes.“",
     x:["Stören, bis das Spiel keinen Spaß mehr macht","„Dann frage ich eben NIE wieder!“"],
     tipp:"Ein Nein ist kein Nein für immer – und es ist kein Urteil über dich."},
    {kontext:"Du erzählst begeistert von deinem Hobby. Ein Kind sagt: „Das ist doch langweilig!“",
     f:"Was denkst du am besten?", r:"„MIR macht es Spaß – und das reicht.“",
     x:["„Dann erzähle ich nie wieder etwas.“","„Ich brauche coolere Hobbys.“"],
     tipp:"Nicht jeder muss toll finden, was du magst – du magst ja auch nicht alles von anderen."},
    {f:"Woran erkennst du einen ECHTEN Freund?",
     r:"Er mag dich auch dann, wenn du mal einen Fehler machst",
     x:["Er will, dass du alles genauso machst wie er","Er lacht, wenn dir etwas misslingt"],
     tipp:"Bei echten Freunden musst du dich nicht verstellen."},
    {kontext:"Fast alle in der Klasse sammeln gerade dieselben Karten. Du findest sie eigentlich langweilig – kaufst sie aber trotzdem.",
     f:"Was steckt dahinter – und was stimmt wirklich?", r:"Der Wunsch dazuzugehören – aber du gehörst auch OHNE gleiche Sachen dazu",
     x:["Gleiche Karten machen automatisch Freunde","Du brauchst einfach MEHR Karten als die anderen"],
     tipp:"Dazugehören kommt vom Mitmachen und Freundlich-Sein – nicht vom Gleich-Sein."},
    {kontext:"Im Stuhlkreis reden alle durcheinander. Du willst etwas Wichtiges sagen.",
     f:"Was wirkt am besten?", r:"Melden, kurz warten – dann ruhig und deutlich sprechen",
     x:["Am lautesten von allen sein","Beleidigt schweigen"],
     tipp:"Ruhig und deutlich schlägt laut und wild – dann hören dir wirklich alle zu."},
    {f:"Du hast beim Spiel verloren und die anderen jubeln. Was ist stark?",
     r:"„Glückwunsch! Nächstes Mal gewinne ich.“",
     x:["Schimpfen und das Spielfeld verlassen","Die anderen Schummler nennen"],
     tipp:"Gut verlieren können beeindruckt mehr als jeder Sieg – ehrlich!"},
    {kontext:"Ein neues Kind ist in der Klasse und kennt noch niemanden.",
     f:"Was wäre ein starker erster Schritt von dir?", r:"„Hallo, ich bin … – willst du in der Pause mit uns spielen?“",
     x:["Abwarten, ob es überhaupt cool ist","Das können ja die anderen machen"],
     tipp:"Wer auf andere zugeht, wirkt stark – und gewinnt oft einen Freund."},
    {f:"Jemand ärgert dich mit Absicht, damit du ausrastest. Was ist die stärkste Antwort?",
     r:"Ruhig bleiben, weggehen – und wenn es nicht aufhört, Hilfe holen",
     x:["Zurückärgern, bis er aufgibt","Sofort losschreien"],
     tipp:"Wer dich ärgert, will deine Wut sehen. Bekommt er sie nicht, verliert er die Lust."},
    {kontext:"Du übst seit Wochen Schach und wirst richtig gut. Ein Kind sagt: „Schach ist was für Langweiler.“",
     f:"Was antwortest du selbstbewusst und freundlich?", r:"„Ich mag es. Willst du mal eine Partie gegen mich probieren?“",
     x:["„Stimmt … ich höre lieber auf.“","„Du bist doch selbst langweilig!“"],
     tipp:"Zu deinem Hobby stehen UND freundlich bleiben – das ist echtes Selbstbewusstsein."},
    {kontext:"Ben spielt in der Pause Fußball mit. Ein Kind sagt: „Du müsstest bei den Kleinen spielen!“",
     f:"Was ist eine starke Antwort?", r:"„Ich spiele, um Spaß zu haben – und der ist genau richtig für mich.“",
     x:["Nie wieder mitspielen","„Du bist doch selbst schlecht!“"],
     tipp:"So ein Spruch sagt nichts über dich. Wer mitspielt, wird besser – wer aufhört, nicht. Und wer andere klein macht, ist selbst gerade nicht stark."},
    {kontext:"Bens Freunde trainieren zwei- bis dreimal pro Woche im Verein. Ben nicht – und er merkt den Unterschied.",
     f:"Was stimmt wirklich?", r:"Sie sind weiter, weil sie mehr ÜBEN – nicht, weil Ben weniger wert ist",
     x:["Ben ist einfach als Mensch schlechter","Mitspielen darf nur, wer im Verein ist"],
     tipp:"Übung macht den Unterschied – niemals der Wert eines Menschen. Der Bolzplatz gehört allen, die Lust haben."},
    {kontext:"Ben traut sich nicht auf den Fußballplatz, weil die anderen besser sind.",
     f:"Was hilft Ben wirklich weiter?", r:"Trotzdem hingehen – oder die Freunde zu SEINEM Lieblingsspiel einladen",
     x:["Zu Hause bleiben, bis er perfekt ist","So tun, als wäre Fußball sowieso doof"],
     tipp:"Mut wächst beim Machen, nicht beim Warten. Und Freundschaft braucht keinen Fußballplatz – sie kann genauso bei DEINEM Spiel entstehen."},
    {f:"Jemand ist in etwas viel besser als du. Was bedeutet das?",
     r:"Er hat darin mehr geübt – du bist dafür in anderen Dingen stark",
     x:["Er ist der bessere Mensch","Du solltest ganz aufgeben"],
     tipp:"Jeder hat sein Ding: Der eine kickt, der andere kennt jeden Schachzug, angelt oder baut Welten. Alles davon zählt."},
    {kontext:"Beim Raufen sagt Ben „Stopp!“ – aber das andere Kind macht einfach weiter.",
     f:"Was ist jetzt richtig?", r:"Laut und deutlich nochmal „Stopp!“ – und wenn es nicht hört: weggehen und einem Erwachsenen sagen",
     x:["Einfach aushalten, sonst ist man eine Memme","Zurückhauen, so fest es geht"],
     tipp:"DEIN Stopp gilt genauso wie das der anderen. Hilfe holen ist kein Petzen, wenn jemand deine Grenze ignoriert."},
    {kontext:"Nach dem Spielen mit Jan fühlt sich Ben oft schlecht: Jan bestimmt alles und lacht über Bens Fehler.",
     f:"Woran merkt man, dass eine Freundschaft nicht guttut?", r:"Wenn du dich nach dem Spielen oft schlechter fühlst als vorher",
     x:["Wenn man nicht jeden Tag zusammen spielt","Das gibt es nicht – Freund ist Freund"],
     tipp:"Echte Freunde geben dir Kraft. Du darfst dir Freunde suchen, bei denen du dich wohlfühlst – das ist keine Untreue."},
    {f:"Was bedeutet Erfolg wirklich – für DICH?",
     r:"Wenn ich etwas besser kann als gestern oder mich etwas getraut habe",
     x:["Wenn alle klatschen und zuschauen","Besser sein als alle anderen"],
     tipp:"Erfolg misst man an sich selbst, nicht an den anderen. Dein Maßstab bist du von gestern."},
    {kontext:"Die Aufgabe wirkt riesig – Ben denkt: „Das schaffe ich NIE!“",
     f:"Was hilft, wenn etwas aussichtslos wirkt?", r:"In Mini-Schritte zerlegen und nur den ersten kleinen Schritt machen",
     x:["Sofort aufgeben – ist eh zu schwer","Warten, bis es jemand anderes macht"],
     tipp:"Kein Berg wird auf einmal bestiegen. Schritt eins reicht für heute – wie bei deinen Mini-Missionen!"},
    {f:"Leo sagt: „Sei ein Stehauf-Löwe!“ Was meint er damit?",
     r:"Nach einem blöden Tag wieder aufstehen und weitermachen",
     x:["Niemals traurig sein dürfen","Immer und überall gewinnen"],
     tipp:"Stark ist nicht, wer nie hinfällt – stark ist, wer wieder aufsteht. Traurig sein ist erlaubt!"},
    {kontext:"In einer Gruppe darfst du nur dabei sein, wenn du dich ständig beweist: immer cool, immer witzig, immer mutig.",
     f:"Was stimmt über echte Freunde?", r:"Bei echten Freunden musst du dir deinen Platz nicht verdienen – du darfst DU sein",
     x:["Dazugehören muss man sich eben verdienen","Dann streng dich mehr an, um cool zu wirken"],
     tipp:"Es geht nicht um die größte Gruppe – sondern um ein paar Menschen, denen du wirklich vertrauen kannst."},
    {kontext:"Am Bach sagt ein Kind: „Spring über die Steine! Trau dich – alle machen das!“ Ben findet es zu gefährlich.",
     f:"Was ist wirklich mutig?", r:"„Nein, das ist mir zu gefährlich“ sagen – und gehen",
     x:["Springen, damit keiner lacht","Warten, bis keiner hinschaut, und es heimlich versuchen"],
     tipp:"Weggehen braucht oft MEHR Mut als Mitmachen. Niemand, der dich mag, verlangt etwas Gefährliches von dir."},
    {kontext:"Die anderen bohren nach: „Warum willst du nicht? Sag schon! Nenn einen Grund!“",
     f:"Was reicht als Antwort?", r:"„Nein. Ich will das nicht.“ – das genügt",
     x:["Eine lange Ausrede erfinden","Doch mitmachen, damit die Fragerei aufhört"],
     tipp:"Dein Nein ist genug. Du schuldest niemandem eine Begründung für deine Grenze."},
    {kontext:"Tom merkt: Seit er viel mit Nick unterwegs ist, redet er gemeiner über andere – genau wie Nick.",
     f:"Was ist hier wichtig zu wissen?", r:"Freunde färben ab – such dir welche, deren Art du gut findest",
     x:["Wie man redet, ist reiner Zufall","Hauptsache, man hat überhaupt Freunde"],
     tipp:"Freunde beeinflussen, was sich normal anfühlt. Bleib nah bei Menschen, die dich besser machen."}
  ]
};
export const STARK_SAETZE=[
  "Ich bin gut, so wie ich bin.",
  "Ich muss nicht so sein wie die anderen.",
  "Ich darf Fehler machen – daraus lerne ich.",
  "Ich frage freundlich – das wirkt.",
  "Echte Freunde mögen mich wegen MIR.",
  "Ich kann warten, bis ich dran bin.",
  "Ich sage, was ich fühle.",
  "Neues auszuprobieren ist mutig.",
  "Zuhören macht mich stark.",
  "Ein Lächeln öffnet Türen.",
  "Ich bleibe ruhig, auch wenn es schwer ist.",
  "Heute mache ich etwas, das MIR Spaß macht.",
  "Ich vergleiche mich mit mir von gestern – nicht mit anderen.",
  "Ich darf üben, statt perfekt zu sein.",
  "Weggehen kann mutiger sein als mitmachen.",
  "Mein Nein ist genug."
];
export const STARK_BEREICHE = [
  { key: "stark", emoji: "💪", name: "Stark mit Leo" },
];
